services:
  - type: web
    name: pixel-post
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Pixel Post
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: pixel-post-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pixel-post-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: pixel-post-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: pixel-post-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pixel-post-db
          property: password

databases:
  - name: pixel-post-db
    engine: mysql
    version: "8.0"
    plan: free