services:
  - type: web
    name: pixel-post
    runtime: php
    runtimeVersion: 8.2
    buildCommand: bash build.sh
    startCommand: vendor/bin/heroku-php-apache2 public/
    disk:
      - name: data
        mountPath: /var/data
