services:
  - type: web
    name: pixel-post
    runtime: php
    runtimeVersion: 8.2
    buildCommand: composer install --no-dev && npm install && npm run build && php artisan migrate --force && php artisan config:cache
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
    disk:
      - name: data
        mountPath: /var/data
